# Generated by Django 6.0.6 on 2026-06-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='House Name')),
                ('info', models.TextField(verbose_name='House Info')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('room_count', models.IntegerField(verbose_name='Room Count')),
                ('people_count', models.IntegerField(verbose_name='People Count')),
                ('square', models.IntegerField(verbose_name='Square')),
                ('price_by_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price by Day')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is Booked')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10, verbose_name='Status')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.housemodel', verbose_name='House')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
